# Generated by Django 5.1.3 on 2024-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
