# Generated by Django 5.1.3 on 2024-11-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='pancard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
