# Generated by Django 5.1.3 on 2024-11-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_contact_city_contact_pancard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=20)),
                ('mothername', models.CharField(max_length=20)),
                ('standard', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('marks', models.IntegerField(max_length=8)),
            ],
        ),
    ]
