# Generated by Django 5.1.3 on 2024-11-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
