# Generated by Django 5.1.3 on 2024-11-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_employee_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
