# Generated by Django 5.1.3 on 2024-11-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_student_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='custom_id',
        ),
    ]
