# Generated by Django 5.1.3 on 2024-11-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_alter_student_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='serial_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='serial_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='serial_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='serial_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
