# Generated by Django 5.1.3 on 2024-11-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_remove_student_custom_id_contact_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
