# Generated by Django 5.1.3 on 2024-11-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_alter_task_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='serial_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
