# Generated by Django 5.1.3 on 2024-11-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_alter_task_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
