# Generated by Django 5.1.3 on 2024-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_contact_profile_picture_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeename',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
